MerryMeals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import marketplace
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('marketplace/', include('marketplace.urls')),
    path('', include('accounts.urls')),
    path('cart/<slug:vendor_slug>', marketplace.views.cart, name= 'cart'),
    path('carts/', marketplace.views.user_carts, name='user_carts'),
    path('search/', marketplace.views.search, name='search'),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.myAccount),
    path('registerUser/', views.registerUser, name='registerUser'),
    path('registerVendor/', views.registerVendor, name='registerVendor'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name= 'logout'),
    path('myAccount/', views.myAccount, name= 'myAccount'),
    path('customerDashboard/', views.customerDashboard, name='customerDashboard'),
    path('vendorDashboard/', views.vendorDashboard, name='vendorDashboard'),
    # For activating the user
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    # For implementing forgot password functionality
    path('forgot_password/', views.forgot_password, name= 'forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name= 'reset_password_validate'),
    path('reset_password/', views.reset_password, name= 'reset_password'),

    #  Path for vendor sidebar
    path('vendor/', include('vendor.urls'))
]

accounts/forms.py
from django import forms
from .models import User, UserProfile
from .validators import allow_only_images_validator

class UserRegisterationForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput()) 
    confirm_password= forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model= User
        fields= ['first_name', 'last_name', 'username', 'email', 'password', 'confirm_password']

    def clean(self):
        cleaned_data= super(UserRegisterationForm, self).clean()
        password= cleaned_data.get('password')
        confirm_passowrd= cleaned_data.get('confirm_password')

        if password!= confirm_passowrd:
            raise forms.ValidationError(
                "Password does not match!"
            )

class UserProfileForm(forms.ModelForm):
    address=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Start typing.. ', 'required': 'required'}))
    profile_picture= forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}), validators=[allow_only_images_validator], required=False)
    cover_photo= forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}), validators=[allow_only_images_validator], required=False)
    latitude= forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    longitude= forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    
    class Meta:
        model= UserProfile
        fields=['profile_picture', 'cover_photo', 'address', 'city', 'state', 'country', 'pin_code', 'longitude', 'latitude']

    # To make some fields read only
    # def __init__(self, *args, ** kwargs):
    #     super(UserProfileForm, self).__init__(*args, **kwargs)
    #     for field in self.fields:
    #         if field =='latitude' or field=='longitude':
    #             self.fields[field].widget.attrs['readonly']= True

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Merry Meals</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<!-- JAVASCRIPT -->
	{% if '/profile/' in request.GET %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	{% endif %}
	<!-- To include sweet alerts on detailed menu page -->
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>

	<!-- GOOGLE MAPS API-->
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" async defer></script>

	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

<body>
	<!--Main Wrapper-->
	<div class="wrapper">
		<!-- Header Start -->
		<header id="header">
			<div class="main-header">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
							<div class="logo">
								<figure>
									<a href="index.html" class="light-logo">
										<img src="{% static 'extra-images/main-logo.png' %}" alt="FoodBakery">
									</a>
								</figure>
							</div>
							<!-- <div class="main-nav">
									<nav id="site-navigation" class="main-navigation">
										<ul>
											<li>
												<a href="#">Demos</a>
												<ul>
													<li><a href="index.html">Food Bakery</a></li>
													<li><a href="mexican-restaurant.html">Mexican Restaurant</a></li>
													<li><a href="foodstop.html">Food Stop</a></li>
													<li><a href="rtl.html">Rtl Demo</a></li>
													<li><a href="food-cout.html">Food Court</a></li>
													<li><a href="single-restaurant.html">Single Restaurant Demo</a></li>
												</ul>  -->
												<!--End Sub Menu -->
											<!--</li>
											<li><a href="listings.html">Restaurants</a></li>
											<li>
												<a href="#">Pages</a>
												<ul>
													<li><a href="price-plans.html">Price Plans</a></li>
													<li><a href="how-it-works.html">How it works</a></li>
													<li><a href="faq.html">FAQ’s</a></li>
													<li><a href="404.html">404</a></li>
													<li><a href="search-result.html">Search Result</a></li>
													<li><a href="contact-us.html">Contact</a></li>
												</ul>-->
												<!--End Sub Menu -->
											<!--</li>
											<li>
												<a href="#">Blogs</a>
												<ul>
													<li><a href="blog-large.html">Blog Large</a></li>
													<li><a href="blog-medium.html">Blog Medium</a></li>
													<li><a href="blog-masonry.html">Blog Masonry</a></li>
													<li><a href="blog-detail.html">Blog Detail Page</a></li>
												</ul>-->
												<!--End Sub Menu -->
											<!--</li>
										</ul>
									</nav>
								</div> -->
							
							<div class="main-location">
								<ul>
									<li class="location-has-children choose-location">
										<form action="#">
											<input type="text" value="" name="location" id= "location" placeholder="Your current location" autocomplete="off">
											<span id="foodbakery_radius_location_open" class="foodbakery-radius-location" onclick="getLocation()"><i class="icon-target5"></i></span>
										</form>
										
									</li>
								</ul>
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
							<div class="login-option">
							{% if user.is_authenticated %}
								<a href="{% url 'user_carts' %}" class="href">
									<i class="fa fa-shopping-cart text-danger" style="font-size: 20px;"></i>
									<span class="badge badge-warning" id="cart_counter" style="border-radius: 50px; position: relative; bottom:10px; left: -5px;">{{cart_count}}</span>
								</a>
							{% endif %}
							
								<a href="{% url 'marketplace' %}" class="btn btn-outline-danger text-uppercase font-weight-bold">Marketplace</a>
								{% if user.is_authenticated %}
							    <a class="cs-color cs-popup-joinus-btn login-popup"  href="{% url 'myAccount' %}">My account</a>
								<a class="cs-color cs-popup-joinus-btn login-popup text-danger"  href="{% url 'logout' %}">Logout</a>
							{% else %}
								<a class="cs-color cs-popup-joinus-btn login-popup"  href="{% url 'login' %}">Login</a>
								<a class="cs-color cs-popup-joinus-btn login-popup"  href="{% url 'registerUser' %}">Register</a>
								<a class="get-start-btn" href="{% url 'registerVendor' %}"> Register Restaurant </a>
							{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
		<!-- Header End -->

        {% block content %}
           <!--MAIN CONTENT GOES HERE -->
        {% endblock %}

        <!-- Footer Start -->
		<footer id="footer" class="footer-style-2">
			<div class="footer-widget">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="widget widget-newsletter">
								<div class="widget-title">
									<h5>Subscribe to our Newsletter</h5>
								</div>
								<div class="fieldset">
									<form action="#">
										<div class="field-holder">
											<label>
												<i class=" icon-envelope3"></i>
												<input type="text" class="field-input" placeholder=" Enter Your Email Address...">
											</label>
										</div>
										<div class="field-holder btn-holder">
											<input class="subscribe-btn bgcolor" type="submit" value="Sign Up">
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copyright-sec">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="copyright-inner">
								<div class="copy-right">
									<p>© 2024 Foodbakery. All Rights Reserved. Developed By <a href="#">LIPIKA GUPTA</a>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- /.cs-copyright -->
		</footer>
		<!-- Footer End -->
	</div>
	
	<!-- Modal Popup End -->
	<script src="{% static 'js/scripts.js' %}"></script>
	<script src="{% static 'js/functions.js' %}"></script>

</body>
<script>
	var x = document.getElementById("location");
	var current_location= sessionStorage.getItem("current_location")
	if (current_location!=""){
		x.value = current_location;
	}
	function getLocation() {
	  if (navigator.geolocation) {
		navigator.geolocation.getCurrentPosition(showPosition);
	  } 
	  else { 
		x.innerHTML = "Geolocation is not supported by this browser.";
	  }
	}
	
	function showPosition(position) {
		var lat= position.coords.latitude;
		var lng = position.coords.longitude;

		//hit ajax request to google maps api endpoint and get the location data using latitude and longitude
		var GOOGLE_API_KEY= "{{GOOGLE_API_KEY}}"
		var url= "https://maps.googleapis.com/maps/api/geocode/json?latlng="+lat+","+lng+"+&key="+ GOOGLE_API_KEY
		$.ajax(
			{
				url: url,
				type: "GET",
				success: function(response){
					var current_location= response.results[0].formatted_address 
					x.value= current_location
					sessionStorage.setItem("current_location", current_location)
					window.location= '?lat='+lat+'&lng='+lng
				}
			}

		)
	}

	</script>

</html>

templates/customerDashboard.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section restaurant-detail-image-section" style=" background: url({% static 'extra-images/cover-photo01.jpg' %}) no-repeat scroll 0 0 / cover;">
        <!-- Container Start -->
        <div class="container">
            <!-- Row Start -->
            <div class="row">
                <!-- Column Start -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="company-info-detail">
                        <div class="company-info">
                            <div class="img-holder">
                                <figure>
                                    <img src="{% static 'extra-images/listing-logo18.png' %}" alt="">
                                </figure>
                            </div>

                            <div class="text-holder">
                                <span class="restaurant-title">Rathan Kumar</span>
                                <div class="text">
                                    <i class="icon-location"></i>
                                    <p>9871435610</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Column End -->
            </div>
            <!-- Row End -->
        </div>
        <!-- Container End -->
    </div>
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!-- Load sidebar here  -->
                    {% include 'includes/customer_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="row">
                                    <div class="element-title has-border right-filters-row">
                                        <h5>Recent Orders</h5>
                                        <div class="right-filters row pull-right">
                                            <div class="col-lg-6 col-md-6 col-xs-6">
                                                <div class="input-field">
                                                    <select class="chosen-select-no-single">
                                                        <option selected="selected" value="">Select Orders Status</option>
                                                        <option value="Processing">Processing</option>
                                                        <option value="Cancelled">Cancelled</option>
                                                        <option value="Completed">Completed</option>
                                                    </select>
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="user-orders-list">
                                        <div class="responsive-table">
                                            <ul class="table-generic">
                                                <li class="order-heading-titles">
                                                    <div>Order id</div>
                                                    <div>Date</div>
                                                    <div>Total Price</div>
                                                    <div>Charges</div>
                                                    <div>Received</div>
                                                    <div>Status</div>
                                                </li>
                                                <li class="order-heading-titles">
                                                    <div><a href="#" data-toggle="modal" data-target="#order-det-22606">order-22606</a></div>
                                                    <div>Apr 9,2020</div>
                                                    <div>£ 38.99</div>
                                                    <div>£ 3.90</div>
                                                    <div>£ 35.09</div>
                                                    <div><span class="order-status" style="background-color: #047a06;">Completed</span></div>
                                                </li>
                                                
                                                
                                                
                                                <li class="order-heading-titles">
                                                    <div><a href="#" data-toggle="modal" data-target="#order-det-22606">order-22583</a></div>
                                                    <div>Apr 9,2020</div>
                                                    <div>£ 26.22</div>
                                                    <div>£ 2.62</div>
                                                    <div>£ 23.60</div>
                                                    <div><span class="order-status" style="background-color: #1e73be;">Processing</span></div>
                                                </li>
                                                <li class="order-heading-titles">
                                                    <div><a href="#" data-toggle="modal" data-target="#order-det-22606">order-22493</a></div>
                                                    <div>Apr 2,2020</div>
                                                    <div>£ 28.24</div>
                                                    <div>£ 2.82</div>
                                                    <div>£ 25.42</div>
                                                    <div><span class="order-status" style="background-color: #047a06;">Completed</span></div>
                                                </li>
                                            </ul>

                                        </div>												
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}

templates/dashboard.html
dashboard

templates/home.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
		<!-- Main Section Start -->
		<div class="main-section">
			<!-- Home Pages Elements Strat -->
			<!-- Main Search Start -->
			<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="element-title">
								<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
									We are in the business of food<br>our restaurants do</h1>
								<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
								We serves the freshly prepared food from renowned restaurants delivered at your location on time.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="main-search fancy bg-holder">
								<form action="{% url 'search' %}" method="GET">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
											<div class="field-holder">
												<input type="text" name="keyword" placeholder="Resturant/Food Name" class="form-control">
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
											<div class="field-holder">
												<ul>
													<li class="select-location">
														<div class="foodbakery-locations-fields-group foodbakery-focus-out">
															<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
															<span id="foodbakery_radius_location_open333" class="foodbakery-radius-location"><i class="icon-target5"></i></span>
															<input type="text" name="address" class="location-field-text filter" id="id_address" placeholder="All Locations">
															<input type="hidden" name="lat" value="" id="id_latitude">
															<input type="hidden" name="lng" value="" id="id_longitude">
														</div>
													</li>
												</ul>
											</div>
										</div>
										<!-- JavaScript Code to implement the google autocomplete place functionality  -->
										<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" async defer></script>
										<script>
										let autocomplete;
										function initAutoComplete(){
											autocomplete= new google.maps.places.Autocomplete(
												document.getElementById('id_address'),{
													types: ['geocode', 'estabilishment'],
													componentRestrictions: {'country': ['in']},
												}
											)
											autocomplete.addListener('place_changed', onPlaceChanged);
										}
										function onPlaceChanged(){
											var place= autocomplete.getPlace();
											if(!place.geometry){
												document.getElementById('id_address').placeholder= "Start Tying...";
											}
											else{
												document.getElementById('id_address').innerHTML= place.name;
											}

											//Assign other address realted fields like state, country, pincode, latitude and longitude
											var geocoder= new Google.maps.Geocoder()
											geocoder.geocode({'address': address}, function(results, status){
												if (status == google.maps.GeocoderStatus.OK) {
													var latitude = results[0].geometry.location.lat();
													var longitude = results[0].geometry.location.lng();
													document.getElementById('id_latitude').value = latitude;
													document.getElementById('id_longitude').value = longitude;        
												}
											});
										}
										</script>
										<div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
											<div class="field-holder">
												<select name="radius" id="radius" style="height:50px;" required>
													<option value="" selected>Choose radius</option>
													<option value="5">5 km</option>
													<option value="10">10 km</option>
													<option value="15">15 km</option>
													<option value="50">50 km</option>
													<option value="75">75 km</option>
													<option value="100">100 km</option>
												</select>
											</div>
										</div>
										<div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
											<div class="field-holder">
												<input type="submit" value="Search">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
						
					</div>
				</div>
			</div>
			<!-- Main Search End -->
			
			<!-- Top Restarurants Section Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-left">
								<h2>Top Restaurants</h2>
								<p>Explore restaurants, bars, and cafés by locality</p>
							</div>
						</div>
						{% for vendor in vendors %}
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="company-logo">
								<ul>
									<li class="has-border">
										<figure>
											<a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{{vendor.user_profile.get_profile_picture_url}}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>
								</ul>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
			<!-- Top Restarurants Section End -->
			<!-- Choose From Most Popular Listin Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-center">
								<h2>Choose From Most Popular Restaurants</h2>
								<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
							</div>
						</div>
						{% for vendor in vendors %}
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="listing fancy">
								<ul class="row">
									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder">
												<figure><a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{{vendor.user_profile.get_profile_picture_url}}" class="img-thumb wp-post-image" alt=""></a></figure>
												<span class="restaurant-status close">
													<em class="bookmarkRibbon"></em>Close
												</span>
											</div>
											<div class="text-holder">
												<div class="post-title">	
													<h5>
														<a href="{% url 'vendor_detail' vendor.vendor_slug %}">{{vendor.vendor_name}}</a>
													</h5>
												</div>
												{% if vendor.user_profile.address %}
                            						<div class="text">
                                						<p>{{vendor.user_profile.address}}</p>
                            						</div>
                            					{% endif %}

												{% if vendor.kms %}<br>
												    <span><small><b>{{vendor.kms}}</b> kms away</small></span>
												{% endif %}
											</div>
											
										</div>
									</li>
								</ul>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
			<!-- Choose From Most Popular Listing End -->

			<!-- Home Pages Elements End  -->
		</div>
		<!-- Main Section End -->
	{% endblock %}